{
 "title": "grafana-dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Reviews Submitted Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(reviews_submitted_total[10h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions Made by Label",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(predictions_latency_seconds_bucket[5h])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Reviews Pending Confirmation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(reviews_pending_confirmation[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Reviews Submitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reviews_submitted_total", "legendFormat": "__auto" }
   ]
  }
 ]
}