apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: small-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.56.90-192.168.56.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - small-pool