services:
  app-service:
    image: ghcr.io/remla2025-team9/app-service:latest
    ports:
      - "5000:5000"
    env_file:
      - ./env-files/app-service.env
    depends_on:
      - model-service
    restart: on-failure

  model-service:
    image: ghcr.io/remla2025-team9/model-service:latest
    environment:
      - SECRETS_FILE=/run/secrets/example-secret
    env_file:
      - ./env-files/model-service.env
    restart: on-failure
    volumes:
      - model-cache:/root/.cache
    secrets:
      - example-secret

  app-frontend:
    image: ghcr.io/remla2025-team9/app-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./env-files/app-frontend.env
    restart: on-failure

volumes:
  model-cache:

secrets:
  example-secret:
    file: ./secrets/example-secret.txt