modelService:
  replicas: 1
  image:
    repository: ghcr.io/remla2025-team9/model-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 5001
  config:
    MODEL_VERSION: "v0.0.3-pre.0"
    SERVICE_PORT: "5001"
    SERVICE_HOST: "0.0.0.0"
  persistence:
    size: 1Gi

appService:
  replicas: 1
  image:
    repository: ghcr.io/remla2025-team9/app-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 5000
  service:
    port: 80
  ingress: 
    host: "localhost"
  config:
    MODEL_SERVICE_URL: "http://model-service:5001"
    FLASK_ENV: "production"
    FLASK_RUN_HOST: "0.0.0.0"
    FLASK_RUN_PORT: "5000"

appFrontend:
  replicas: 1
  image:
    repository: ghcr.io/remla2025-team9/app-frontend
    tag: latest
    pullPolicy: IfNotPresent
  port: 3000
  service:
    port: 80
  ingress:
    host: "localhost"
  config:
    APP_SERVICE_URL: "/app-service"

appSecret:
  enabled: true
  apiKey: "top_secret_message_of_team_9"
