# model-service settings
modelService:
  replicas: 1
  image:
    repository: ghcr.io/remla2025-team9/model-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 5001
  config:
    MODEL_VERSION: "v0.0.3-pre.0"
    SERVICE_PORT: "5001"
    SERVICE_HOST: "0.0.0.0"
  # secretName: example-secret
  persistence:
    size: 1Gi

# app-service settings
appService:
  replicas: 1
  image:
    repository: ghcr.io/remla2025-team9/app-service
    tag: latest
    pullPolicy: Always
  port: 5000
  service:
    port: 80
  ingress: 
    host: "app-service.k8s.local"
  config:
    MODEL_SERVICE_URL: "http://model-service:5001"
    FLASK_ENV: "production"
    FLASK_RUN_HOST: "0.0.0.0"
    FLASK_RUN_PORT: "5000"

# app-frontend settings
appFrontend:
  replicas: 1
  image:
    repository: ghcr.io/remla2025-team9/app-frontend
    tag: latest
    pullPolicy: IfNotPresent
  port: 3000 # Internal port the container listens on
  service:
    port: 80 # Service port for Ingress to target
  ingress:
    host: "app-frontend.k8s.local"
  config:
    APP_SERVICE_URL: "http://app-service.k8s.local"

appSecret:
  enabled: true
  apiKey: "top_secret_message_of_team_9"

# grafana settings
grafana:
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "grafana-dashboards"


