# Global version settings that allow for one canary deployment and traffic splitting between stable and canary version.
versions:
  stable:
    versionLabel: "stable"
    # The destinationWeight is used to control the traffic split between stable and canary versions.
    destinationWeight: 10
  canary:
    # This setting enables canary deployments for every service that supports it.
    enabled: true
    versionLabel: "canary"
    # The destinationWeight is used to control the traffic split between stable and canary versions.
    destinationWeight: 90

# model-service settings
modelService:
  # This setting is used to set the DNS name for the model service as required by the assignment.
  dnsName: model-service
  replicas: 1
  stable:
    image:
      tag: latest
    config:
      MODEL_VERSION: "v0.0.3-pre.0"
      SERVICE_PORT: "5001"
      SERVICE_HOST: "0.0.0.0"
  # Canary deployment settings specific to the model service.
  canary:
    # This setting enables a canary deployment for the model service.
    enabled: true
    image:
      tag: canary
    config:
      MODEL_VERSION: "v0.0.3-pre.0"
      SERVICE_PORT: "5001"
      SERVICE_HOST: "0.0.0.0"
  image:
    repository: ghcr.io/remla2025-team9/model-service
    pullPolicy: Always
  port: 5001
  persistence:
    size: 1Gi

# app-service settings
appService:
  replicas: 1
  stable:
    image:
      tag: latest
    config:
      # The MODEL_SERVICE_URL is set in the configMap of the app-service as it can't be resolved in values.yaml
      FLASK_ENV: "production"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
      APP_VERSION_LABEL: "stable" # Label used by Prometheus to identify the version
  # Canary deployment settings specific to the app service.
  canary:
    # This setting enables a canary deployment for the app service.
    enabled: true
    image:
      tag: canary
    config:
      # The MODEL_SERVICE_URL is set in the configMap of the app-service as it can't be resolved in values.yaml
      FLASK_ENV: "production"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
      APP_VERSION_LABEL: "canary" # Label used by Prometheus to identify the version
  image:
    repository: ghcr.io/remla2025-team9/app-service
    pullPolicy: Always
  port: 5000
  service:
    port: 80
  ingress:
    host: "app-service.k8s.local"

# app-frontend settings
appFrontend:
  replicas: 1
  stable:
    image:
      tag: latest
    config:
      # Additional environment variables for the stable version of the app frontend. Currently empty.
  # Canary deployment settings specific to the app frontend.
  canary:
    # This setting enables a canary deployment for the app frontend.
    enabled: true
    image:
      tag: canary
    config:
      # Additional environment variables for the stable version of the app frontend. Currently empty.
  image:
    repository: ghcr.io/remla2025-team9/app-frontend
    pullPolicy: Always
  port: 3000 # Internal port the container listens on
  service:
    port: 80 # Service port for Ingress to target
  ingress:
    host: "app-frontend.k8s.local"

appSecret:
  enabled: true
  apiKey: "top_secret_message_of_team_9"

# grafana settings
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "grafana-dashboards"

kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
      createSecret:
        enabled: false
        annotations:
          sidecar.istio.io/inject: "false"
      patch:
        enabled: false
        annotations:
          sidecar.istio.io/inject: "false"
    tls:
      enabled: false
