# model-service settings
modelService:
  image:
    repository: ghcr.io/remla2025-team9/model-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 5001
  config:
    MODEL_VERSION: "v0.0.3-pre.0"
    SERVICE_PORT: "5001"
    SERVICE_HOST: "0.0.0.0"
  # secretName: example-secret
  persistence:
    size: 1Gi

# app-service settings
appService:
  image:
    repository: ghcr.io/remla2025-team9/app-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 5000
  config:
    MODEL_SERVICE_URL: "http://model-service:5001"
    FLASK_ENV: "production"
    FLASK_RUN_HOST: "0.0.0.0"
    FLASK_RUN_PORT: "5000"

# app-frontend settings
appFrontend:
  image:
    repository: ghcr.io/remla2025-team9/app-frontend
    tag: latest
    pullPolicy: IfNotPresent
  port: 3000 # Internal port the container listens on
  service:
    port: 80 # Service port for Ingress to target
  config:
    APP_SERVICE_URL: "http://app-service:5000" 