apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-app-frontend-virtualservice
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app-frontend
spec:
  hosts:
    - {{ .Values.appFrontend.ingress.host | quote }}
  gateways:
    - {{ .Release.Name }}-my-istio-gateway
  http:
    - name: "route-if-stable-cookie"
      match:
        - headers:
            Cookie:
              regex: ".*app-frontend-version={{ .Values.appFrontend.stable.versionLabel }}.*"
      route:
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.appFrontend.stable.versionLabel }}
    - name: "route-if-canary-cookie"
      match:
        - headers:
            Cookie:
              regex: ".*app-frontend-version={{ .Values.appFrontend.canary.versionLabel }}.*"
      route:
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.appFrontend.canary.versionLabel }}
    - name: "default-route-and-set-cookie"
      route:
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.appFrontend.stable.versionLabel }}
          weight: {{ .Values.appFrontend.stable.destinationWeight }}
          headers:
            response:
              add:
                "Set-Cookie": "app-frontend-version={{ .Values.appFrontend.stable.versionLabel }}; Path=/; Max-Age=2592000"
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.appFrontend.canary.versionLabel }}
          weight: {{ .Values.appFrontend.canary.destinationWeight }}
          headers:
            response:
              add:
                "Set-Cookie": "app-frontend-version={{ .Values.appFrontend.canary.versionLabel }}; Path=/; Max-Age=2592000"