apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-app-frontend-dr
spec:
  host: {{ .Release.Name }}-app-frontend
  subsets:
    - name: {{ .Values.appFrontend.stable.versionLabel }}
      labels:
        version: {{ .Values.appFrontend.stable.versionLabel }}
    - name: {{ .Values.appFrontend.canary.versionLabel }}
      labels:
        version: {{ .Values.appFrontend.canary.versionLabel }}

