apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
  labels:
   app: app-frontend
spec:
  # type: ClusterIP
  ports:
    - port: {{ .Values.appFrontend.service.port }}
      targetPort: {{ .Values.appFrontend.port }}
  selector:
    app: app-frontend