apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-app-service-dr
spec:
  host: {{ .Release.Name }}-app-service
  subsets:
    - name: {{ .Values.versions.stable.versionLabel }}
      labels:
        version: {{ .Values.versions.stable.versionLabel }}
    {{- if and .Values.appService.canary.enabled .Values.versions.canary.enabled }}
    - name: {{ .Values.versions.canary.versionLabel }}
      labels:
        version: {{ .Values.versions.canary.versionLabel }}
    {{- end }}