apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-helm-chart.fullname" . }}-app-frontend
  labels:
   app: {{ include "app-helm-chart.fullname" . }}-app-frontend
spec:
  ports:
    - port: {{ .Values.appFrontend.service.port }}
      targetPort: {{ .Values.appFrontend.port }}
  selector:
    app: {{ include "app-helm-chart.fullname" . }}-app-frontend