apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  ports:
    - port: {{ .Values.appService.service.port }}
      targetPort: {{ .Values.appService.port }}
      name: http
  selector:
    app: app-service
