apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-app-service-vs
spec:
  hosts:
    - {{ .Values.appService.ingress.host | quote }}
  gateways:
    - {{ .Release.Name }}-my-istio-gateway
  http:
    - name: "route-if-stable-header"
      match:
        - headers:
            X-App-Version:
              exact: {{ .Values.versions.stable.versionLabel }}
      route:
        - destination:
            host: {{ .Release.Name }}-app-service
            subset: {{ .Values.versions.stable.versionLabel }}
    
    {{- if and .Values.appService.canary.enabled .Values.versions.canary.enabled }}
    - name: "route-if-canary-header"
      match:
        - headers:
            X-App-Version:
              exact: {{ .Values.versions.canary.versionLabel }}
      route:
        - destination:
            host: {{ .Release.Name }}-app-service
            subset: {{ .Values.versions.canary.versionLabel }}
    {{- end }}
    
    # This route handles requests without a specific version header.
    - name: "default-route"
      route:
        - destination:
            host: {{ .Release.Name }}-app-service
            subset: {{ .Values.versions.stable.versionLabel }}