apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-frontend-virtualservice
  namespace: {{ .Values.namespace }}
  labels:
    app: app-frontend
spec:
  hosts:
    - {{ .Values.appFrontend.ingress.host | quote }}
  gateways:
    - my-istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: v2
          weight: 10
        - destination:
            host: app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: v1
          weight: 90