apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service-dr
spec:
  host: app-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-user
  subsets:
    - name: {{ .Values.appService.stable.versionLabel }}
      labels:
        version: {{ .Values.appService.stable.versionLabel }}
    {{- if .Values.appService.canary.enabled }}
    - name: {{ .Values.appService.canary.versionLabel }}
      labels:
        version: {{ .Values.appService.canary.versionLabel }}
    {{- end }}
