apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-service-vs
spec:
  hosts:
    - {{ .Values.appService.ingress.host | quote }}
  gateways:
    - my-istio-gateway
  http:
    - route:
        - destination:
              host: app-service
              subset: v2
          weight: 10
        - destination:
            host: app-service
            subset: v1
          weight: 90
