apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  labels:
    app: {{ .Release.Name }}-app-service
spec:
  ports:
    - port: {{ .Values.appService.service.port }}
      targetPort: {{ .Values.appService.port }}
      name: http
  selector:
    app: {{ .Release.Name }}-app-service
