apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  # type: ClusterIP
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.port }}
  selector:
    app: app-service