apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-app-frontend-virtualservice
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app-frontend
spec:
  hosts:
    - {{ .Values.appFrontend.ingress.host | quote }}
  gateways:
    - {{ .Release.Name }}-my-istio-gateway
  http:
    - name: "route-if-stable-cookie"
      match:
        - headers:
            Cookie:
              regex: ".*app-version={{ .Values.versions.stable.versionLabel }}.*"
      route:
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.versions.stable.versionLabel }}
    
    {{- if and .Values.appFrontend.canary.enabled .Values.versions.canary.enabled }}
    - name: "route-if-canary-cookie"
      match:
        - headers:
            Cookie:
              regex: ".*app-version={{ .Values.versions.canary.versionLabel }}.*"
      route:
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.versions.canary.versionLabel }}
    {{- end }}
    
    - name: "default-route-and-set-cookie"
      route:
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.versions.stable.versionLabel }}
          weight: {{ if and .Values.appFrontend.canary.enabled .Values.versions.canary.enabled }}{{ .Values.versions.stable.destinationWeight }}{{ else }}100{{ end }}
          headers:
            response:
              add:
                "Set-Cookie": "app-version={{ .Values.versions.stable.versionLabel }}; Path=/; Max-Age=2592000"
        
        {{- if and .Values.appFrontend.canary.enabled .Values.versions.canary.enabled }}
        - destination:
            host: {{ .Release.Name }}-app-frontend
            port:
              number: {{ .Values.appFrontend.service.port }}
            subset: {{ .Values.versions.canary.versionLabel }}
          weight: {{ .Values.versions.canary.destinationWeight }}
          headers:
            response:
              add:
                "Set-Cookie": "app-version={{ .Values.versions.canary.versionLabel }}; Path=/; Max-Age=2592000"
        {{- end }}