apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-frontend
  labels:
   app: {{ .Release.Name }}-app-frontend
spec:
  ports:
    - port: {{ .Values.appFrontend.service.port }}
      targetPort: {{ .Values.appFrontend.port }}
      name: http
  selector:
    app: {{ .Release.Name }}-app-frontend