apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-helm-chart.fullname" . }}-app-service
  labels:
    app: {{ include "app-helm-chart.fullname" . }}-app-service
spec:
  ports:
    - port: {{ .Values.appService.service.port }}
      targetPort: {{ .Values.appService.port }}
  selector:
    app: {{ include "app-helm-chart.fullname" . }}-app-service