apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-service-ingress
  labels:
    app: app-service
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.appService.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: {{ .Values.appService.service.port }}