apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-helm-chart.fullname" . }}-frontend-config
  labels:
    app: {{ include "app-helm-chart.fullname" . }}-frontend
data:
  {{- range $key, $val := .Values.appFrontend.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-helm-chart.fullname" . }}-frontend-deployment
  labels:
    app: {{ include "app-helm-chart.fullname" . }}-frontend
spec:
  replicas: {{ .Values.appFrontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "app-helm-chart.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "app-helm-chart.fullname" . }}-frontend
    spec:
      restartPolicy: Always
      containers:
        - name: app-frontend
          image: "{{ .Values.appFrontend.image.repository }}:{{ .Values.appFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.appFrontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appFrontend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "app-helm-chart.fullname" . }}-frontend-config
