apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-service-vs
spec:
  hosts:
    - {{ .Values.appService.stable.host | quote }}
    {{- if .Values.appService.canary.enabled }}
    - {{ .Values.appService.canary.host | quote }}
    {{- end }}
  gateways:
    - my-istio-gateway
  http:
    - match:
        - authority:
            exact: {{ .Values.appService.stable.host | quote }}
      route:
        - destination:
            host: app-service
            subset: {{ .Values.appService.stable.versionLabel }}
    
    {{- if .Values.appService.canary.enabled }}
    - match:
        - authority:
            exact: {{ .Values.appService.canary.host | quote }}
      route:
        - destination:
            host: app-service
            subset: {{ .Values.appService.canary.versionLabel }}
    {{- end }}
