{{- if .Values.appSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
type: Opaque
stringData:
  API_KEY: {{ .Values.appSecret.apiKey | quote }}
{{- end }}

