apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-frontend-ingress
  labels:
    app: {{ .Release.Name }}-app-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.appFrontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-frontend
                port:
                  number: {{ .Values.appFrontend.service.port }}
