apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc
  labels:
    app: model-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelService.persistence.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-cache-pv
  labels:
    app: model-service
spec:
  capacity:
    storage: {{ .Values.modelService.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/model-cache
