{{- if .Values.modelService.persistence.size }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-model-cache-pvc
  labels:
    app: {{ .Release.Name }}-model-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.modelService.persistence.size }}
{{- end }}
