apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service
spec:
  # type: ClusterIP
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  selector:
    app: model-service