---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-service-config
  labels:
    app: {{ .Release.Name }}-model-service
data:
  {{- range $key, $val := .Values.modelService.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-model-cache-pvc
  labels:
    app: {{ .Release.Name }}-model-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-helm-chart.fullname" . }}-model-service-deployment
  labels:
    app: {{ include "app-helm-chart.fullname" . }}-model-service
spec:
  replicas: {{ .Values.modelService.replicas }}
  selector:
    matchLabels:
      app: {{ include "app-helm-chart.fullname" . }}-model-service
  template:
    metadata:
      labels:
        app: {{ include "app-helm-chart.fullname" . }}-model-service
    spec:
      restartPolicy: Always
      containers:
        - name: model-service
          image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.image.tag }}"
          imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.modelService.port }}
          envFrom:
            - configMapRef:
                name: model-service-config
          volumeMounts:
            - name: model-cache-storage
              mountPath: /root/.cache
      volumes:
        - name: model-cache-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-model-cache-pvc

