apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-model-cache-pv-{{ .Values.modelService.stable.versionLabel }}
  labels:
    app: model-service
spec:
  capacity:
    storage: {{ .Values.modelService.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/shared/{{ .Release.Name }}-model-cache-{{ .Values.modelService.stable.versionLabel }}
---
{{- if .Values.modelService.canary.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-model-cache-pv-{{ .Values.modelService.canary.versionLabel }}
  labels:
    app: model-service
spec:
  capacity:
    storage: {{ .Values.modelService.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/shared/{{ .Release.Name }}-model-cache-{{ .Values.modelService.canary.versionLabel }}
{{- end }}