apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.dnsName }}-dr
spec:
  host: {{ .Release.Name }}-{{ .Values.modelService.dnsName }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-user
  subsets:
    - name: {{ .Values.versions.stable.versionLabel }}
      labels:
        version: {{ .Values.versions.stable.versionLabel }}
    {{- if and .Values.modelService.canary.enabled .Values.versions.canary.enabled }}
    - name: {{ .Values.versions.canary.versionLabel }}
      labels:
        version: {{ .Values.versions.canary.versionLabel }}
    {{- end }}
