apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.dns-name }}-vs
spec:
  hosts:
    - {{ .Release.Name }}-{{ .Values.modelService.dns-name }}
  http:
    - match:
        - sourceLabels:
            app: {{ .Release.Name }}-app-service
            version: {{ .Values.appService.canary.versionLabel }}
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.dns-name }}
            subset: {{ .Values.modelService.canary.versionLabel }}
    - route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.dns-name }}
            subset: {{ .Values.modelService.stable.versionLabel }}