apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: model-service-vs
spec:
  hosts:
    - model-service
  http:
    - match:
        - sourceLabels:
            app: app-service
            version: {{ .Values.appService.canary.versionLabel }}
      route:
        - destination:
            host: model-service
            subset: {{ .Values.modelService.canary.versionLabel }}
    - route:
        - destination:
            host: model-service
            subset: {{ .Values.modelService.stable.versionLabel }}