apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-helm-chart.fullname" . }}-model-service
  labels:
    app: {{ include "app-helm-chart.fullname" . }}-model-service
spec:
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  selector:
    app: {{ include "app-helm-chart.fullname" . }}-model-service