apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: model-cache-pv-v1
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: model-cache-pv-v2
  storageClassName: manual
