apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelService.dns-name }}
  labels:
    app: {{ .Values.modelService.dns-name }}
spec:
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  selector:
    app: {{ .Values.modelService.dns-name }}