apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.modelService.name }}-dr
spec:
  host: {{ .Values.modelService.name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-user
  subsets:
    - name: {{ .Values.modelService.stable.versionLabel }}
      labels:
        version: {{ .Values.modelService.stable.versionLabel }}
    {{- if .Values.modelService.canary.enabled }}
    - name: {{ .Values.modelService.canary.versionLabel }}
      labels:
        version: {{ .Values.modelService.canary.versionLabel }}
    {{- end }}
