apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-app-service-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-app-service
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-service
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-reviews-submitted-alert
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-app-service
    release: {{ .Release.Name }}
spec:
  groups:
    - name: reviews-submitted.rules
      rules:
        - alert: ReviewsSubmittedHigh
          expr: increase(reviews_submitted_total[5m]) > 5
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "High number of reviews submitted"
            description: "More than 5 reviews have been submitted in the last 5 minutes."
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-alertmanager-secret
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ .Release.Name }}-app-service
type: Opaque
stringData:
  smtp_auth_username: {{ .Values.alertCreds.username | quote }}
  smtp_auth_password: {{ .Values.alertCreds.password | quote }}
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Release.Name }}-reviews-submitted-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  image: quay.io/prometheus/alertmanager:v0.25.0
  version: v0.25.0
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: main
  serviceAccountName: prometheus-k8s
  routePrefix: /
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Release.Name }}-email-config
  namespace: {{ .Release.Namespace }}
  labels:
    alertmanagerConfig: main
spec:
  route:
    receiver: email-receiver
  receivers:
    - name: email-receiver
      emailConfigs:
        - to: remla2025team9.alerts@gmail.com
          from: {{ .Values.alertCreds.username }}
          smarthost: smtp.gmail.com:587
          authUsername: {{ .Values.alertCreds.username }}
          authPassword:
            name: {{ .Release.Name }}-alertmanager-secret
            key: smtp_auth_password
          requireTLS: true