---
- hosts: all
  become: yes
  gather_facts: no
  environment:
    KUBECONFIG: /home/vagrant/.kube/config

  tasks:
    - name: Copy configuration files
      ansible.builtin.copy:
        src: yamls/
        dest: /home/vagrant/yamls/
        remote_src: no
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Install MetalLB
      ansible.builtin.command: |
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/refs/tags/v0.14.9/config/manifests/metallb-native.yaml

    - name: Wait for MetalLB controller to be ready
      ansible.builtin.command: |
        kubectl wait -n metallb-system -l app=metallb,component=controller \
          --for=condition=ready pod --timeout=120s

    - name: Apply MetalLB configuration
      ansible.builtin.command: |
        kubectl apply -f yamls/metallb-config.yaml

    - name: Add Helm repo ingress-nginx
      kubernetes.core.helm_repository:
        name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx

    - name: Install NGINX Ingress Controller
      kubernetes.core.helm:
        update_repo_cache: true
        release_name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: yes
        release_state: present
        values:
          controller:
            service:
              LoadBalancerIP: 192.168.56.90

    - name: Add Helm repo cert-manager
      kubernetes.core.helm_repository:
        name: jetstack
        url: https://charts.jetstack.io

    - name: Install cert-manager
      kubernetes.core.helm:
        update_repo_cache: true
        release_name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: yes
        release_state: present
        values:
          installCRDs: true
        wait: yes
        wait_timeout: 300s

    - name: Configure cert-manager issuers
      ansible.builtin.command: |
        kubectl apply -f yamls/cert-manager-issuers.yaml

    - name: Add Helm repo kubernetes-dashboard
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        url: https://kubernetes.github.io/dashboard/

    - name: Install Kubernetes Dashboard
      kubernetes.core.helm:
        update_repo_cache: true
        release_name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: yes
        release_state: present
        wait: yes
        wait_timeout: 300s

    - name: Apply Dashboard RBAC manifest
      ansible.builtin.command: |
          kubectl apply -f yamls/dashboard-rbac.yaml


    - name: Apply Dashboard Ingress manifest
      ansible.builtin.command: |
          kubectl apply -f yamls/dashboard-ingress.yaml

    - name: Add monitoring stack helm repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts

    - name: Install monitoring stack
      kubernetes.core.helm:
          update_repo_cache: true
          release_name: prometheus
          chart_ref: prometheus-community/kube-prometheus-stack
          release_namespace: monitoring
          create_namespace: yes
          release_state: present
