---
- hosts: nodes
  become: true
  tasks: 
    - name: Generate kubeadm join command on controller
      ansible.builtin.command: kubeadm token create --print-join-command
      register: kubeadm_join_command
      delegate_to: "{{ groups['control'][0] }}"
      run_once: true
      changed_when: false
      check_mode: false
      vars:
        ansible_delegated_vars:
          ansible_become: yes 

    - name: Join worker nodes to the Kubernetes cluster
      ansible.builtin.shell: "{{ hostvars[groups['control'][0]]['kubeadm_join_command']['stdout'] }}"