- name: Setup Kubernetes controller node
  hosts: ctrl
  become: yes

  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

  tasks:
    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes