---
- hosts: all
  become: yes

  vars:
    ssh_key_pattern: "{{ playbook_dir }}/../ssh/*.pub"          # relative to your playbook root

  tasks:
    - name: Ensure vagrant user exists
      user:
        name: vagrant
        state: present
        shell: /bin/bash

    - name: Ensure .ssh directory exists
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Add Vagrant's SSH public keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ lookup('fileglob', ssh_key_pattern, wantlist=True) }}"
  
    - name: Disable SWAP in the system
      ansible.builtin.shell: swapoff -a
      ignore_errors: yes

    - name: Remove SWAP from fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^\s*[^#]+\s+none\s+swap\s+'
    
    - name: br_netfilter automated loading
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
    
    - name: Add the br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present
    
    - name: Enable ipv4 forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
    
    - name: Enable net.bridge.bridge-nf-call-iptables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
    
    - name: Enable net.bridge.bridge-nf-call-ip6tables
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes
    
    - name: Render the /etc/hosts file
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
    
    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    
    - name: Add signing key for Kubernetes
      ansible.builtin.api_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present
    
    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: >-
         deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
        filename: kubernetes-community
        state: present
    
    - name: Refresh APT cache
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - containerd=1.7.24
          - runc=1.1.12
          - kubeadm=1.32.4
          - kubelet=1.32.4
          - kubectl=1.32.4
        state: present
        update_cache: yes